apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: vendor/docker/bitnami/kafka:3.6.1-debian-11-r6
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 9094
        env:
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-0.kafka-headless:9093"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,SSL://:9094,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka-headless:9092,SSL://kafka-0.kafka-headless:9094"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,SSL:SSL,CONTROLLER:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "abcdefghijklmnopqrstuv"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_SSL_KEYSTORE_LOCATION
          value: "/opt/bitnami/kafka/config/certs/keystore.jks"
        - name: KAFKA_CFG_SSL_KEYSTORE_PASSWORD
          value: "secret"
        - name: KAFKA_CFG_SSL_TRUSTSTORE_LOCATION
          value: "/opt/bitnami/kafka/config/certs/truststore.jks"
        - name: KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD
          value: "secret"
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka
        - name: kafka-certificates
          mountPath: /opt/bitnami/kafka/config/certs
          readOnly: true
      volumes:
      - name: kafka-certificates
        secret:
          secretName: kafka-certificates
          defaultMode: 0400
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
