apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka-0.kafka-headless:9093
    listeners=PLAINTEXT://:9092,SSL://:9094,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-0.kafka-headless:9092,SSL://kafka-0.kafka-headless:9094
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,CONTROLLER:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT
    controller.listener.names=CONTROLLER
    ssl.keystore.location=/opt/bitnami/kafka/config/certs/keystore.jks
    ssl.keystore.password=secret
    ssl.truststore.location=/opt/bitnami/kafka/config/certs/truststore.jks
    ssl.truststore.password=secret
    allow.plaintext.listener=yes
    kafka.kraft.cluster.id=abcdefghijklmnopqrstuv
    node.id=1
    socket.request.max.bytes=419430400
    replica.fetch.max.bytes=419430400
    message.max.bytes=419430400
    max.request.size=419430400
    max.partition.fetch.bytes=419430400
